### ISSUE TITLE
For better experience for usage

### ISSUE THREAD

**Issue by huang12zheng** [chanhx/crabviz#10]
When I click on an item, it becomes relevant only to that item.
But if I click on a blank space (or scroll the canvas), it becomes all relevant.

Here are some ideas:
* Lock
If I can right-click or something .To make the canvas lock only one item,
* Change the canvas by double-clicking
make clicking the blank canvas doesn't become all relevant. 
Or double-click directly to change the interface
* Or allow the keyboard to move the canvas to make mouse or touch is no need.
 
----
当我点击一项时,它变为只会这一项有关.
但如果我点空白的地方(或者拉动画布),就会变为全部相关.
我有一些想法:
* 锁定
如果可以右键或别的方法,来让界面锁定只有一项,
* 变化界面通过双击
暂时让点空白画布不会变为全部相关.或者直接双击才对界面有变化
* 或者支持键盘移动画布
* 而避免 要移动画布时, 鼠标或触摸对界面改变.

这可能是#9的一个复制

**Comment by chanhx** [comment]
I just made a commit (9cbd72c19405cb48cab9185a760a69bea5dd5145) to distinguish between mouse clicks and drags. Now the focus won't get cleared when dragging the graph.

**Comment by huang12zheng** [comment]
I look forward to your release to the vscode marketplace

**Comment by chanhx** [comment]
Hey, version 0.1.1 is released, which includes a fix for the dragging issue. Hope you like it!
