### ISSUE TITLE
what vscode version need

### ISSUE THREAD

**Issue by figo361** [chanhx/crabviz#12]
![image](https://github.com/chanhx/crabviz/assets/6834921/7a8ba66f-c857-4ee7-936d-aeebe0d9faec)

**Comment by chanhx** [comment]
According to the `package.json`, it should be 1.77.0 or higher.

The version was added automatically when I created the project, and I have not tested the minimum supported version thoroughly. It's possible a lower version of VS Code would still be compatible with the extension. I will try to test with lower versions and adjust the range later.
