### ISSUE TITLE
failed to work well with clangd

### ISSUE THREAD

**Issue by LimingFang** [chanhx/crabviz#13]
C++, clangd, and when i clicked `generate call graph`, nothing happened.

**Comment by LimingFang** [comment]
Hi, thanks for replay. After I clicked, nothing happened, including the text "Crabviz: Generating call graph"

**Comment by chanhx** [comment]
Could you provide a link to a GitHub repository or a minimal code example that reproduces the problem?

**Comment by LimingFang** [comment]
somehow it worked well when I used it in another two repos😇. Thanks!
