### ISSUE TITLE
Feature request: Call graph with the current function

### ISSUE THREAD

**Issue by Zhaotianzheng** [chanhx/crabviz#18]
这插件简直梦中情插，只不过我之前用的是source insight，一直想要找一个类似下面这个repo 中的 visual studio 插件的效果：
https://github.com/league1991/CodeAtlasVsix
就那种点哪儿就跳哪儿那种。
当然，单纯用 call hierarchy 也行，可是就想看图。。只恨我自己太菜，啥rust啥都不懂，球球了，大佬让我白嫖下吧(狗头保命)

**Comment by chanhx** [comment]
单函数的调用图是计划要支持的，我尽量早点做吧，不过最近不太有空，这个功能还得等等。

**Comment by chanhx** [comment]
刚发了新版本 v0.3.0，包含这个功能，现在可以升级体验一下了。
