### ISSUE TITLE
Does not seem to work with Python3

### ISSUE THREAD

**Issue by darkpandarts** [chanhx/crabviz#24]
Looks amazing! But, Does this work with Python3? I get "no matching workspace symbols" errors. I think these were due to my __init__.py files which I deleted. However, no image is opening in vscode. Any ideas on how to get it working? Would be much appreciated :)

**Comment by chanhx** [comment]
Try [this](https://stackoverflow.com/a/77371861), it works for me.

**Comment by darkpandarts** [comment]
Thanks for the link. I uninstalled pylance and installed the prelease version: `
v2023.11.102`, & reinstalled crabviz.

Still get the type error with empty __init__.py files. after removing said files, and running crabviz from right clicl, no type errors but crabviz does not open or show anything.

Do you have any ideas on what may being wrong? :)

**Comment by chanhx** [comment]
Is the code open-source? Or could you provide a minimal reproducible example?

**Comment by darkpandarts** [comment]
it is open source. the project is here

**Comment by darkpandarts** [comment]
if using pip install using requirements-old.txt

**Comment by darkpandarts** [comment]
entrypoint is `gen_mkdocs_site.py` and main src files are in `bashautodoc`

**Comment by chanhx** [comment]
OK, I will test it later.

**Comment by chanhx** [comment]
I just cloned your code and analyzed the `bashautodoc` folder with Crabviz, no pip install, and then I got the output below. Maybe you should check about the pylance settings.

![bashautodoc](https://github.com/chanhx/crabviz/assets/20551552/2cb53637-dc7c-4b9e-a138-af096334ba3d)

**Comment by darkpandarts** [comment]
Ok that sounds amazing! :) What version of pylance do you have installed? i currently have `v2023.11.102`
![Selection_108](https://github.com/chanhx/crabviz/assets/114529342/7d6c8d98-f76d-47f4-ad46-4d57531e97c0)

**Comment by chanhx** [comment]
It's not about the version. I switched to the pre-release version, and it worked too. Maybe you should check about [Python settings](https://code.visualstudio.com/docs/python/settings-reference#_python-language-server-settings), I just modified the `Python: Language Server` and `Python: Default Interpreter Path`.

**Comment by chanhx** [comment]
@jonathanGGa could you provide an example?

**Comment by chanhx** [comment]
There is an activation error in v0.3.0, which I think is the cause of this issue.

The bug should be fixed in the new version 0.3.1. Please update and try it out.

**Comment by darkpandarts** [comment]
Awesome! It works for me now thanks! You are a ⭐!!!
