### ISSUE TITLE
bug: doesn't work for some function

### ISSUE THREAD

**Issue by lucky9-cyou** [chanhx/crabviz#26]
The crabviz doesn't work for some function, like `finish_task` in following image:
![image](https://github.com/chanhx/crabviz/assets/56758695/657e1835-b3db-46d1-830e-c5a238ccf36a)

**Comment by chanhx** [comment]
Please check about incoming calls of `Task::update_task_status_result` and `Resource::finish_task` to see if `finish_task` is there. (right click on the function name, select “Show Call Hierarchy” on the context menu, and then switch to show incoming calls.)

**Comment by lucky9-cyou** [comment]
when i open `finish_task` call graph, it will show following result:
![image](https://github.com/chanhx/crabviz/assets/56758695/c0a2d96b-bf4e-4b0f-bd19-59a3dd47c00d)
The call graph is right, but why didn't it appear in previous image?

**Comment by chanhx** [comment]
Crabviz fetches just incoming calls when generating call graphs for selected files. While generating call graphs for selected functions, Crabviz fetches both incoming calls and outgoing calls.

I guess maybe those two calls are returned in outgoing calls, but not in incoming calls.

So, please help check about call hierarchies of these functions, show incoming calls of `Task::update_task_status_result` and `Resource::finish_task`, and outgoing calls of `finish_task`.

<img width="361" alt="image" src="https://github.com/chanhx/crabviz/assets/20551552/d8bdc0ac-93d2-4d9a-a002-7e9bb94ab06c">

**Comment by lucky9-cyou** [comment]
The outgoing calls of `finish_task` are as follows:
![image](https://github.com/chanhx/crabviz/assets/56758695/18f67998-e5c3-49be-a8c3-07f5b33019d9)
The incomming calls of `Task::update_task_status_result` is as follows:
![image](https://github.com/chanhx/crabviz/assets/56758695/e510dde2-63ae-4c62-b6cd-b59b5bfa1a1f)
The incoming calls of `Resource::finish_task` is as follows:
![image](https://github.com/chanhx/crabviz/assets/56758695/41c3108c-cf6c-49ff-a625-53924a46495b)

**Comment by lucky9-cyou** [comment]
> Crabviz fetches just incoming calls when generating call graphs for selected files. While generating call graphs for selected functions, Crabviz fetches both incoming calls and outgoing calls.
> 
> I guess maybe those two calls are returned in outgoing calls, but not in incoming calls.
> 
> So, please help check about call hierarchies of these functions, show incoming calls of `Task::update_task_status_result` and `Resource::finish_task`, and outgoing calls of `finish_task`.
> 
> <img alt="image" width="361" src="https://private-user-images.githubusercontent.com/20551552/307593215-d8bdc0ac-93d2-4d9a-a002-7e9bb94ab06c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzA0NzUsIm5iZiI6MTcwODkzMDE3NSwicGF0aCI6Ii8yMDU1MTU1Mi8zMDc1OTMyMTUtZDhiZGMwYWMtOTNkMi00ZDlhLWEwMDItN2U5YmI5NGFiMDZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA2NDkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxNDdhODg2NDQyNTIwOGQ3MzY0ZDRiODJjN2RkMzI0MWM5ZWFlNDBjNjIxMWU0MjQxNTU4OTc4YWNlN2U1NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rMjMHW8K_OwHZ5bBbV2DiINmMBCayL2D5TSMsvYWPvc">

It might be possible to add some options, so that when generating a call graph for selected files, it fetches both incoming calls and outgoing calls.

**Comment by chanhx** [comment]
Thank you so much! The language server does return the calling relationships which were not drawn on the graph. Is this bug reproducible? If yes, then is the code open source? Or could you provide a minimal reproducible sample? Many thanks!

> It might be possible to add some options, so that when generating a call graph for selected files, it fetches both incoming calls and outgoing calls.

There are cases that calls are returned in incoming calls but not in outgoing calls, and not vice-versa. So just fetching incoming calls should be enough.

**Comment by lucky9-cyou** [comment]
I try to generate a minimal reproducible sample, but it doesn't work. The call graph of `finish_task` will show. And when I delete other function in my project, the call graph of `finish_task` will also show.
![CleanShot 2024-02-26 at 23 59 57@2x](https://github.com/chanhx/crabviz/assets/56758695/bbb6b342-ab9c-4d68-af5e-a50ce90d7615)
![CleanShot 2024-02-27 at 00 02 17@2x](https://github.com/chanhx/crabviz/assets/56758695/b5e0a890-fe8a-46be-836e-d78d3b08fefa)
My code repo is private, but I can invite you as collaborators temporarily.
![CleanShot 2024-02-27 at 00 01 23@2x](https://github.com/chanhx/crabviz/assets/56758695/9c8e2a7c-0b85-487e-a878-f4a1a1f8da9b)
Thanks for your help very much.

**Comment by chanhx** [comment]
I just tested crabviz on your project, and I think it worked as expected. Here is the output graph.

![service](https://github.com/chanhx/crabviz/assets/20551552/5fff9d74-746b-442f-bf48-48be74257b4e)

All information is from the language server, so you should wait till the language server is ready before generating a call graph.

<img width="200" alt="image" src="https://github.com/chanhx/crabviz/assets/20551552/512cc0ad-ce46-4cfd-bc31-5357a3ed277b">

**Comment by lucky9-cyou** [comment]
This is very strange, my language server is already prepared. Could this possibly be related to the version of the toolchain or rust-analyzer?
My toolchain version is 1.77.0 nightly, my rust-analyzer version is v0.3.1860.

**Comment by lucky9-cyou** [comment]
when i try it in another computer with 1.78.0 nightly, it still doesn't show call graph of `finish_task`:
![CleanShot 2024-02-27 at 14 01 29@2x](https://github.com/chanhx/crabviz/assets/56758695/55cf7469-2bea-428a-a53e-982b2c296c50)

**Comment by chanhx** [comment]
Same RA version here, and toolchain version is `1.78.0-nightly (fc3800f65 2024-02-26)`, no issues.

Please check the call hierarchies again, if the results are as expected, then run crabviz again to generate a new call graph.

**Comment by lucky9-cyou** [comment]
I still get the wrong results, and I'm not quite sure why that is. Anyway, thank you for your patient help and the outstanding project.
