### ISSUE TITLE
Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

### ISSUE THREAD

**Issue by prestonvanloon** [chanhx/crabviz#35]
```
Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

Not sure what else I can provide here. I was trying to generate a call graph in the vs code extension

**Comment by briandiloreto** [comment]
Restarting VS Code after installing the extension solved this issue for me

**Comment by prestonvanloon** [comment]
Yep, same here. Well, I restarted my whole computer but it works again

**Comment by chanhx** [comment]
I haven't seen this error, but seems it can be solved by restarting VS Code (and some cleaning maybe).

Closing this issue as it seems not a problem of the extension.
