### ISSUE TITLE
how to import GraphGenerator

### ISSUE THREAD

**Issue by git-hawk** [chanhx/crabviz#38]
![4baa5fda-9c2a-40ac-8c98-15092735ab5b](https://github.com/user-attachments/assets/21253d3e-e263-497b-bdbb-eca0f3f1f8e1)

**Comment by chanhx** [comment]
You need to install [Rust](https://www.rust-lang.org/tools/install) and [wasm-pack](https://rustwasm.github.io/wasm-pack/installer/), and then run the extension (open the `editors/code` folder in a separate window, and run it), it will compile the Rust code to a WebAssembly package, then you can import it.
