### ISSUE TITLE
Doesn't seem to work with Julia code

### ISSUE THREAD

**Issue by kenahoo** [chanhx/crabviz#45]
Crabviz seems to detect Julia functions fine, but can't detect any of the calls.  Here's a distilled example:

<img width="494" alt="Screenshot 2024-10-15 at 10 45 35 AM" src="https://github.com/user-attachments/assets/402cc2d0-4880-4b1d-81c6-506971ba617b">

I have no idea whether this is a Julia extension problem, or a Crabviz problem.  However, the Julia extension does seem to know what functions are calling what, since I can command-click on the `bar(x)` invocation and it jumps to the definition `function bar(x)...`.

If I had to guess, maybe it has something to do with Julia's multiple dispatch?  Maybe that makes its LSP more complicated?

**Comment by chanhx** [comment]
This is because Crabviz relies on the Call Hierarchy feature provided by language servers to draw edges, but the Julia extension [doesn't support this feature](https://github.com/julia-vscode/julia-vscode/issues/2013).

**Comment by kenahoo** [comment]
Gotcha, thanks for the reply.  I'll see if I can lobby the Julia LSP side of things and see how much work that would be.
