### ISSUE TITLE
Doesn't Identify Calls Through Actix Route

### ISSUE THREAD

**Issue by Torsitano** [chanhx/crabviz#7]
Neat extension, I went to test it on some stuff I had lying around and noticed that it didn't identify functions that were called as routes for Actix. I have a repo that I was using while working through Zero to Production in Rust that I used to test.

I found that when looking at the graph for the entire `src` folder, it shows that my functions for routes are never called:

<img width="554" alt="image" src="https://github.com/chanhx/crabviz/assets/58057426/9a76381a-632f-4b1c-98d3-b807c17bbd3a">

When checking the call hierarchy in VS Code, it correctly shows that this `health_check` function is called by `run`, which is called by `spawn_app` and `main`:

<img width="566" alt="image" src="https://github.com/chanhx/crabviz/assets/58057426/8a6b8ef1-ad79-45cd-8126-0950ac04487e">

Source is here for reference: https://github.com/Torsitano/zero-to-rust/blob/main/src/routes/health_check.rs

**Comment by chanhx** [comment]
Thank you for providing such a detailed report. I use the `vscode.provideOutgoingCalls` command to get the outgoing calls, and it seems it's because `health_check` is not directly called by `run`, so it's not included. I don't know how VS Code gets that, will need some time to figure out how to fix it.

**Comment by chanhx** [comment]
This is fixed in v0.1.2, please update the extension and check it out.

<img width="995" alt="image" src="https://github.com/chanhx/crabviz/assets/20551552/8b5ba9fc-40bf-4eca-b8c6-585697f1740c">
