### ISSUE TITLE
how to save graph

### ISSUE THREAD

**Issue by xiaoosi** [chanhx/crabviz#8]

**Comment by chanhx** [comment]
Export is currently not supported. Exporting SVG with external CSS seems a little bit tricky, but I will work on it in the upcoming version.

**Comment by KshitijSabale** [comment]
yes please add this functionality , as for large call graph I am not able to see the functions , so may be after saving i can zoom into it , i suppose

**Comment by chanhx** [comment]
Version 0.2.0 is just released. You can now export call graphs by right-clicking on them and select "Export Call Graph" in the context menu.
